spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        # Market Data Service - Public APIs
        - id: market-data-public-route
          uri: http://market-data-service:8083
          predicates:
            - Path=/api/market/public/**
          filters:
            - RewritePath=/api/market/public/(?<segment>.*), /api/internal/public/$\{segment}

        # Market Data Service - Private APIs (JWT 필요)
        - id: market-data-private-route
          uri: http://market-data-service:8083
          predicates:
            - Path=/api/market/**
          filters:
            - RewritePath=/api/market/(?<segment>.*), /api/internal/$\{segment}

        # User Service - Auth endpoints (Public)
        - id: user-auth-route
          uri: http://user-service:8080
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /api/internal/auth/$\{segment}

        # User Service - User APIs (JWT 필요)
        - id: user-private-route
          uri: http://user-service:8080
          predicates:
            - Path=/api/users/**,/api/accounts/**
          filters:
            - RewritePath=/api/(?<prefix>users|accounts)/(?<segment>.*), /api/internal/$\{prefix}/$\{segment}

        # Trade Service (JWT 필요)
        - id: trade-route
          uri: http://trade-service:8081
          predicates:
            - Path=/api/trade/**,/api/trade-history/**,/api/portfolio/**
          filters:
            - RewritePath=/api/(?<prefix>trade|trade-history|portfolio)/(?<segment>.*), /api/internal/$\{prefix}/$\{segment}

        # Backtest Service (JWT 필요)
        - id: backtest-route
          uri: http://backtest-service:8082
          predicates:
            - Path=/api/trading-simulation/**,/api/backtest/**,/api/analysis/**
          filters:
            - RewritePath=/api/(?<prefix>trading-simulation|backtest|analysis)/(?<segment>.*), /api/internal/$\{prefix}/$\{segment}

services:
  market-data:
    uri: http://market-data-service:8083
  user:
    uri: http://user-service:8080
  trade:
    uri: http://trade-service:8081
  backtest:
    uri: http://backtest-service:8082

gateway:
  cors:
    allowed-origins: "http://localhost:3000,http://localhost:5173,http://app.localhost,http://172.18.0.6:3000,http://172.18.0.7"

logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.muscat.gateway: INFO
    reactor.netty: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes
  endpoint:
    gateway:
      enabled: true
    routes:
      enabled: true
