spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        # Market Data Service - Public APIs (no auth needed)
        - id: market-data-public-route
          uri: http://market-data-service:8083
          predicates:
            - Path=/api/market/public/**

        # Market Data Service - Private APIs (JWT 필요)
        - id: market-data-private-route
          uri: http://market-data-service:8083
          predicates:
            - Path=/api/market/**
          filters:
            - TokenRelay

        # User Service - Auth endpoints (Public - no auth needed)
        - id: user-auth-route
          uri: http://user-service:8080
          predicates:
            - Path=/api/auth/**

        # User Service - User APIs (JWT 필요)
        - id: user-private-route
          uri: http://user-service:8080
          predicates:
            - Path=/api/users/**,/api/accounts/**
          filters:
            - TokenRelay

        # Trade Service (JWT 필요)
        - id: trade-route
          uri: http://trade-service:8081
          predicates:
            - Path=/api/trade/**,/api/trade-history/**,/api/portfolio/**
          filters:
            - TokenRelay

        # Backtest Service (JWT 필요)
        - id: backtest-route
          uri: http://backtest-service:8082
          predicates:
            - Path=/api/backtest/**,/api/trading-simulation/**,/api/analysis/**
          filters:
            - TokenRelay

        # Backtest Internal API (서비스 간 통신용)
        - id: backtest-internal-route
          uri: http://backtest-service:8082
          predicates:
            - Path=/api/internal/backtest/**

services:
  market-data:
    uri: http://market-data-service:8083
  user:
    uri: http://user-service:8080
  trade:
    uri: http://trade-service:8081
  backtest:
    uri: http://backtest-service:8082

gateway:
  cors:
    allowed-origins: "http://localhost:3000,http://localhost:5173,http://app.localhost,http://172.18.0.6:3000,http://172.18.0.7"

logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.muscat.gateway: INFO
    reactor.netty: WARN

# Management port for health checks and metrics
management:
  server:
    port: 9090  # Separate port for metrics and health checks
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,gateway,routes,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: gateway-server
  endpoint:
    gateway:
      enabled: true
    routes:
      enabled: true
