# Market Data Service - Production Profile

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://ggeolmuse-postgres.cxa6ioco4fhg.ap-northeast-2.rds.amazonaws.com:5432/ggeolmuse_market?sslmode=require}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  h2:
    console:
      enabled: false

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  sql:
    init:
      mode: never

# Provider 설정은 기본 설정(market-data-service.yml) 사용

logging:
  level:
    com.muscat.marketdata: INFO
    org.springframework.security: WARN
