# Market Data Service - Production Profile

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/marketdb}
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}

  h2:
    console:
      enabled: false

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

  sql:
    init:
      mode: never

# Provider 설정은 기본 설정(market-data-service.yml) 사용

logging:
  level:
    com.muscat.marketdata: INFO
    org.springframework.security: WARN
