spring:
  # PostgreSQL RDS (환경변수로 주입)
  datasource:
    url: ${DB_URL_TRADE}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  h2:
    console:
      enabled: false

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

# Keycloak (secret만 프로파일별)
keycloak:
  credentials:
    secret: ${KEYCLOAK_SECRET}

# Logging
logging:
  level:
    com.muscat.trade: INFO
    org.springframework.security: WARN
